### ISSUE TITLE
Create RTL Child Theme

### ISSUE THREAD

**Issue by BesrourMS** [ahmadawais/_child#4]
Hi, I want to create arabic child theme for many wordpress blogging theme but I don't really find a good article about enabling RTL. Please add this feature to your project.
Thanks.

**Comment by ahmadawais** [comment]
Creating an RTL child theme has nothing to with this boilerplate. That has to do with the CSS. You'll have to learn it to do that. This is just a boilerplate to create child themes, it has no say in how you modify your themes.
